// Generated by scripts/import-medium.mjs from https://medium.com/feed/@urbn_hq.
// Do not edit by hand; re-run `npm run import:medium`.
import type { Story } from "./stories";

export const MEDIUM_STORIES: Story[] = [
  {
    "slug": "why-ibadans-growing-property-market-needs-better-information",
    "title": "Why Ibadan’s Growing Property Market Needs Better Information",
    "excerpt": "Imagine a stretch of land on the edge of Ibadan that was once mostly farmland, a few scattered compounds, and one untarred road. A decade later, it could be a…",
    "image": "/images/blog/why-ibadans-growing-property-market-needs-better-information/0.webp",
    "imageAlt": "A man standing on an Urbn billboard above an Ibadan street, under the headline 'Why Ibadan's Growing Property Market Needs Better Information'",
    "category": "Technology",
    "date": "2026-10-05",
    "readMins": 4,
    "body": [
      {
        "type": "p",
        "html": "Imagine a stretch of land on the edge of Ibadan that was once mostly farmland, a few scattered compounds, and one untarred road.<br>A decade later, it could be a developing residential axis — new estates, a school, small businesses, and a property market active enough for agents to list properties there every week.<br>The land changed fast."
      },
      {
        "type": "h",
        "text": "The information describing it didn’t always keep pace."
      },
      {
        "type": "p",
        "html": "The survey may exist. The transaction may exist. The address may have changed. A new building may have replaced an open plot.<br>Whether all of that information is still connected to the property it describes is a different question.<br>That gap is what this article is about — not whether Ibadan is growing, but whether the information keeping track of that growth is growing with it."
      },
      {
        "type": "h",
        "text": "Growth is a physical story. It’s also an information story."
      },
      {
        "type": "p",
        "html": "World Bank analysis puts Ibadan’s built-up area at roughly 83 square kilometres in 1975, 182 in 1990, 202 in 2000, and 348 by 2014. That represents more than a fourfold increase in the city’s built-up area over that period."
      },
      {
        "type": "img",
        "src": "/images/blog/why-ibadans-growing-property-market-needs-better-information/1.webp",
        "alt": "Aerial view of a busy road running through densely built Ibadan neighbourhoods"
      },
      {
        "type": "p",
        "html": "Every added square kilometre came with new parcels, new addresses, new owners, new transactions and new development.<br>Land was subdivided. Buildings replaced open plots. Roads reached areas that had previously been peripheral and changed their relationship with the rest of the city.<br>Each of those changes produced information somewhere."
      },
      {
        "type": "p",
        "html": "A developer needed spatial information before building. A financial institution needed property information before financing. Government needed to understand what existed before making decisions about infrastructure and land use.<br>None of that is unique to buyers and sellers.<br>Property information is part of urban infrastructure"
      },
      {
        "type": "h",
        "text": "More records isn’t the same as better information"
      },
      {
        "type": "p",
        "html": "Take two developing areas on Ibadan’s edge, both with hundreds of new properties over the past decade.<br>In one, records are relatively easy to trace back to the right property. A reference exists, changes can be tracked, and a lawyer or other professional can reconstruct what happened without excessive friction.<br>In the other, information exists in roughly the same volume, but it is scattered: a receipt here, an old agreement there, a survey that needs to be reconciled with what is actually on the ground."
      },
      {
        "type": "p",
        "html": "The difference isn’t necessarily how much development has happened.<br>It is how usable the information is when someone actually needs it."
      },
      {
        "type": "p",
        "html": "That distinction matters as Ibadan keeps expanding.<br>A growing city does not simply generate more buildings. It generates more relationships between land, ownership, addresses, development, infrastructure and time.<br>The information describing those relationships needs to keep up."
      },
      {
        "type": "h",
        "text": "Ibadan already has real infrastructure here"
      },
      {
        "type": "img",
        "src": "/images/blog/why-ibadans-growing-property-market-needs-better-information/2.webp",
        "alt": "Cocoa House, a landmark tower in Ibadan, with a yellow taxi on the road in front"
      },
      {
        "type": "p",
        "html": "Oyo State has built meaningful pieces of this infrastructure.<br>OyoGISS, the state’s geographic information system, captures, stores, manages and analyses geographic data for areas including land administration, urban planning and economic development. Its Property Reference System assigns reference codes to properties and supports property location and addressing."
      },
      {
        "type": "p",
        "html": "Alongside it, the state operates digital property searches that provide information such as ownership history, legal status and encumbrances. Its Digital Land Survey Plan Registry also allows users to check whether a survey plan has been captured in the official digital system."
      },
      {
        "type": "p",
        "html": "These systems matter for more than convenience.<br>They begin turning property information from something people have to dig up piece by piece into something structured around the property itself.<br>That is an important shift for a city that keeps changing."
      },
      {
        "type": "h",
        "text": "This isn’t only a buyer’s problem"
      },
      {
        "type": "p",
        "html": "When government wants to upgrade a neighbourhood — a new road, drainage system or public facility — it needs to understand the area first."
      },
      {
        "type": "p",
        "html": "Where are the properties?<br>How is the land being used?<br>What infrastructure already exists?<br>How has the area changed?"
      },
      {
        "type": "p",
        "html": "Oyo State’s Home Owners Charter connects property enumeration and documentation with broader planning and the provision of public infrastructure."
      },
      {
        "type": "p",
        "html": "The same logic applies to private development.<br>A property’s potential is shaped by what surrounds it: access roads, nearby development, permitted use and existing infrastructure."
      },
      {
        "type": "p",
        "html": "As Ibadan’s edges keep filling in, understanding one property increasingly means understanding its context too."
      },
      {
        "type": "h",
        "text": "What a growing city like Ibadan actually needs next"
      },
      {
        "type": "p",
        "html": "Digitising property information is an important step.<br>But scale changes what “enough” looks like."
      },
      {
        "type": "p",
        "html": "A city whose built-up area expanded from roughly 83 square kilometres to 348 square kilometres between 1975 and 2014 does not just need searchable records. It needs those records to remain connected as the same properties change hands, change use and change over time.<br>That’s where a persistent property reference matters."
      },
      {
        "type": "p",
        "html": "Instead of every transaction, survey or approval existing as its own disconnected fact, each piece of information can be associated with the same underlying property. The history accumulates instead of scattering."
      },
      {
        "type": "p",
        "html": "That is the larger opportunity in digital property identity: not simply putting more property information online, but giving that information a consistent point of reference as the city changes around it."
      },
      {
        "type": "p",
        "html": "Ibadan’s growth was never really the hard part.<br>The harder part is making sure the city’s information can grow at the same speed as the city itself.<br>A bigger city doesn’t just need more property.<br>It needs to actually know the property it already has."
      }
    ],
    "sourceUrl": "https://medium.com/@urbn_hq/why-ibadans-growing-property-market-needs-better-information-1b220f86783b",
    "imageFit": "contain"
  },
  {
    "slug": "from-paper-records-to-digital-property-identity-where-nigerian-real-estate-is-headed",
    "title": "From Paper Records to Digital Property Identity: Where Nigerian Real Estate Is Headed",
    "excerpt": "Paper has a problem. It’s slow to search, easy to misfile, expensive to store at scale, and genuinely difficult to update once the information inside it needs…",
    "image": "/images/blog/from-paper-records-to-digital-property-identity-where-nigerian-real-estate-is-headed/0.webp",
    "imageAlt": "A smiling woman holding property documents beside a phone showing the Urbn app, under the headline 'From Paper Records to Digital Property Identity'",
    "category": "Real Estate",
    "date": "2026-10-02",
    "readMins": 4,
    "body": [
      {
        "type": "p",
        "html": "Paper has a problem. It’s slow to search, easy to misfile, expensive to store at scale, and genuinely difficult to update once the information inside it needs to connect to something else."
      },
      {
        "type": "p",
        "html": "Moving that information onto a screen solves some of that. It doesn’t solve all of it."
      },
      {
        "type": "p",
        "html": "Imagine a land registry has just finished scanning years of old survey files into a searchable digital archive — a real upgrade. But a lawyer running a title search still has to open three separate systems to piece together one property’s full history: the survey in one, the ownership record in another, a transaction from a decade earlier in a third.<br>Each system works exactly as designed. None of them knows about the other two."
      },
      {
        "type": "p",
        "html": "That’s the gap this next stage of digitisation actually needs to close. Not “how do we get more records onto computers,” but “how do we get the computers to agree they’re talking about the same property?”"
      },
      {
        "type": "h",
        "text": "Getting records out of the filing cabinet is the easy part"
      },
      {
        "type": "p",
        "html": "Land administration in Nigeria has leaned heavily on physical documents and manual processes for decades, and the limits of that are well known: old records take time to locate, updates are cumbersome, and information rarely moves easily between departments. Spread a property&#39;s history across several offices, and reconstructing it becomes a project in itself."
      },
      {
        "type": "h",
        "text": "Digitisation changes the mechanics."
      },
      {
        "type": "p",
        "html": "A digital record can be indexed, searched, backed up, and pulled up without anyone walking a file from one desk to another."
      },
      {
        "type": "p",
        "html": "Nigeria is already moving here. The Federal Ministry of Housing and Urban Development has identified fragmented land records, slow titling, and limited access to land information among the challenges in the country&#39;s land administration system, and its Land4Growth programme includes efforts to digitise records and modernise registries.<br>Oyo State is a working example of what that looks like in practice."
      },
      {
        "type": "p",
        "html": "Its Digital Land Survey Plan Registry lets users check whether a survey plan has been captured digitally, while its Property Search service provides information including ownership history, legal status, and encumbrances. Real progress. Also, only the first layer."
      },
      {
        "type": "h",
        "text": "A digital record can still be alone in the room"
      },
      {
        "type": "p",
        "html": "Go back to that lawyer running three separate searches.<br>All three systems were digital. All three were functioning correctly. The work was still, fundamentally, the old work: find the records, lay them side by side, and manually decide whether they’re describing the same piece of land."
      },
      {
        "type": "p",
        "html": "The filing cabinet had disappeared. The fragmentation hadn’t — it had just learned to load faster."
      },
      {
        "type": "p",
        "html": "This is why recent federal policy language has started pushing past digitisation on its own, toward the harmonisation of land administration systems and more integrated digital registries. The target has quietly shifted from “get it online” to “get it talking to the other systems.”"
      },
      {
        "type": "h",
        "text": "What a persistent reference actually changes"
      },
      {
        "type": "p",
        "html": "Picture a property that changes hands.<br>A new transaction creates a new record. The previous owner becomes history; the new owner becomes the current record. The property itself doesn&#39;t change — it&#39;s still the same parcel of land it was before the sale."
      },
      {
        "type": "p",
        "html": "If a system treats every transaction as its own isolated record, someone eventually has to reassemble the chain by hand — exactly what that lawyer was doing across three separate logins."
      },
      {
        "type": "p",
        "html": "If the system instead holds one persistent reference for the property, every new record can be associated with that same reference. The chain doesn&#39;t need reassembling. It was never broken apart in the first place."
      },
      {
        "type": "p",
        "html": "A purely digital system answers one question: Can I find this record?"
      },
      {
        "type": "p",
        "html": "A connected system answers a harder, more useful one: How does this record relate to everything else that&#39;s happened to this property?"
      },
      {
        "type": "p",
        "html": "As more of Nigeria&#39;s property information moves online, that second question is the one that determines whether digitisation has actually made the system more useful."
      },
      {
        "type": "h",
        "text": "A familiar principle, applied somewhere new"
      },
      {
        "type": "p",
        "html": "Nigeria’s National Identification Number offers a useful pattern, even though people are a very different kind of thing to identify than land."
      },
      {
        "type": "p",
        "html": "NIMC describes the NIN as a unique identifier assigned to an individual and used to establish identity across the national identity system.<br>Property doesn’t need anything resembling a NIN. But it can benefit from the same underlying principle: a fixed reference that stays constant while everything attached to it — ownership, documentation, use — keeps changing around it."
      },
      {
        "type": "p",
        "html": "Oyo State’s OyoGISS platform is already a step in this direction. Its Property Reference System assigns reference codes that anchor a property’s location and support its identification across the state’s geographic and property-information infrastructure."
      },
      {
        "type": "p",
        "html": "A reference code on its own isn’t the destination, though."
      },
      {
        "type": "p",
        "html": "The real opportunity is for that reference to become the point future records about the property can be associated with — so a property’s file, over time, starts looking less like a folder of unrelated documents and more like one continuously written history."
      },
      {
        "type": "h",
        "text": "The progression: Paper → Digital → Connected → Persistent"
      },
      {
        "type": "img",
        "src": "/images/blog/from-paper-records-to-digital-property-identity-where-nigerian-real-estate-is-headed/1.webp",
        "alt": "Diagram: Property, then associated records, then history, then verification"
      },
      {
        "type": "p",
        "html": "Paper records need to become searchable digital ones.<br>Digital records need consistent references and the ability to communicate across systems.<br>Connected records need to stay associated with the property itself as ownership and use shift around it over years and decades.<br>And underneath all of it, someone still needs to govern who can create, update, verify, and access what.<br>None of this replaces the lawyer, the surveyor, or the physical inspection."
      },
      {
        "type": "p",
        "html": "Digitising a record doesn’t make an inaccurate one accurate. What it can do is make the environment around a property something a professional can actually navigate, instead of something they have to excavate from three different systems that don’t know each other exist."
      }
    ],
    "sourceUrl": "https://medium.com/@urbn_hq/from-paper-records-to-digital-property-identity-where-nigerian-real-estate-is-headed-6deae0f8e0e3",
    "imageFit": "contain"
  },
  {
    "slug": "why-real-estate-needs-an-identity-layer",
    "title": "Why Real Estate Needs an Identity Layer",
    "excerpt": "A property can have an address, a survey plan, a title document and a transaction history — and still leave you unable to answer one basic question: do all of…",
    "image": "/images/blog/why-real-estate-needs-an-identity-layer/0.webp",
    "imageAlt": "A modern house with a clipboard showing a Property ID record, under the headline 'Why Real Estate Needs an Identity Layer'",
    "category": "Digital Transformation",
    "date": "2026-09-30",
    "readMins": 4,
    "body": [
      {
        "type": "p",
        "html": "A property can have an address, a survey plan, a title document and a transaction history — and still leave you unable to answer one basic question: do all of these actually belong to the same property?"
      },
      {
        "type": "p",
        "html": "That question sits underneath almost every property dispute, every failed financing application, every transaction that takes longer than it should. The documents exist. What&#39;s missing is something that ties them together."
      },
      {
        "type": "p",
        "html": "This is where the idea of a property identity becomes useful."
      },
      {
        "type": "h",
        "text": "Location tells you where. Identity tells you which one."
      },
      {
        "type": "p",
        "html": "An address tells you where a property sits. A survey describes its boundaries. A title establishes an interest. A transaction record shows that something happened."
      },
      {
        "type": "p",
        "html": "None of these, on their own, gives a property a persistent identity across its whole history."
      },
      {
        "type": "p",
        "html": "Think about a passport."
      },
      {
        "type": "p",
        "html": "A person’s address changes. A person’s address, circumstances and other personal information can change over time, but the identifying reference continues to tie different records back to the same individual.<br>Property needs the same principle of continuity."
      },
      {
        "type": "p",
        "html": "A property can change owners, get subdivided, get developed, watch its surroundings transform completely. Through all of it, it should still be recognisable as the same underlying asset — not a new one every time something about it changes."
      },
      {
        "type": "h",
        "text": "What would a property identity actually anchor?"
      },
      {
        "type": "p",
        "html": "A useful property identity would hold together the information that belongs to one specific property: its location, its survey record, its ownership history, its title and related documents, its transaction history, the changes made to it over time, and any interests or restrictions attached to it."
      },
      {
        "type": "p",
        "html": "The value isn&#39;t in having all of this information somewhere. Nigeria already has plenty of records scattered across plenty of systems. The value is in knowing, reliably, which information belongs to which property — so a new transaction doesn&#39;t require reconstructing that property&#39;s entire history from separate, disconnected sources every single time."
      },
      {
        "type": "h",
        "text": "Identity is about continuity, not ownership"
      },
      {
        "type": "p",
        "html": "Picture a property that changes owners three times over twenty years.<br>The ownership record changes each time. The documents change. The people involved change entirely."
      },
      {
        "type": "p",
        "html": "The property itself doesn’t become a new property with each transfer. Its identity is the thread running underneath all three transactions — the reason a buyer in year twenty can still trace what happened in year one, instead of starting from nothing."
      },
      {
        "type": "p",
        "html": "Most real estate transactions aren’t really about a single moment. A buyer is almost always trying to understand what came before: who held an interest, what was transferred, whether the property was ever divided, what else might still be attached to it."
      },
      {
        "type": "p",
        "html": "A persistent identity gives all of that a place to accumulate, instead of scattering with every change of hands."
      },
      {
        "type": "img",
        "src": "/images/blog/why-real-estate-needs-an-identity-layer/1.webp",
        "alt": "Scattered real estate documents, including a listing, a mortgage form and a set of house keys",
        "caption": "scattered real estate documents"
      },
      {
        "type": "h",
        "text": "Identity answers a narrower question than people assume"
      },
      {
        "type": "p",
        "html": "Giving a property a persistent identity doesn’t make every piece of information attached to it accurate."
      },
      {
        "type": "p",
        "html": "A well-identified property can still carry outdated, incomplete, or wrong information — identity and accuracy are solving two different problems."
      },
      {
        "type": "p",
        "html": "Identity settles which property a record belongs to. Verification settles whether that record can be trusted. A strong identity system makes verification faster and more structured. It was never meant to replace it."
      },
      {
        "type": "h",
        "text": "Nigeria is already building pieces of this"
      },
      {
        "type": "p",
        "html": "Oyo State’s OyoGISS platform includes a Property Reference System that assigns reference codes to properties, built to support identification and management of property information across the state. Oyo also runs digital property searches and survey-plan searches alongside it.<br>Each of these tools solves part of the problem. The larger opportunity — the one still largely unbuilt — is making property information persistent and connected across a property’s entire lifecycle, not just searchable in isolated pieces."
      },
      {
        "type": "h",
        "text": "What actually changes with an identity layer"
      },
      {
        "type": "p",
        "html": "Without one, a transaction typically looks like this:"
      },
      {
        "type": "h",
        "text": "Document → search → another document → another search → reconciliation → professional review"
      },
      {
        "type": "img",
        "src": "/images/blog/why-real-estate-needs-an-identity-layer/2.webp",
        "alt": "Diagram: Document, search, another document, another search, reconciliation, then professional review"
      },
      {
        "type": "p",
        "html": "Someone has to manually work out whether everything refers to the same property and how the pieces fit together — every time, for every transaction."
      },
      {
        "type": "p",
        "html": "With a persistent property reference, the starting point shifts:"
      },
      {
        "type": "h",
        "text": "Property → associated records → history → verification"
      },
      {
        "type": "img",
        "src": "/images/blog/why-real-estate-needs-an-identity-layer/3.webp",
        "alt": "Diagram: Property, then associated records, then history, then verification"
      },
      {
        "type": "p",
        "html": "Legal review, surveying, and physical inspection don’t disappear. Professionals still have real work to do. But that work now starts from a clear anchor instead of a pile of documents someone has to first prove belong together."
      },
      {
        "type": "p",
        "html": "That shift matters past any single deal. Owners get a property history that’s easier to maintain. Professionals spend less time reconstructing what already happened. Institutions managing planning and land administration get information they can actually rely on. And buyers get a real starting point, instead of a stack of paper they have to piece into a story themselves."
      },
      {
        "type": "h",
        "text": "A property should carry its own continuity"
      },
      {
        "type": "p",
        "html": "Real estate has always generated records. What it’s never reliably had is a way to keep those records tied to the property they actually describe, as that property moves through decades of owners, uses, and changes."
      },
      {
        "type": "p",
        "html": "That’s what an identity layer is for — not another document to create, but a fixed point the documents that already exist can finally hold onto."
      }
    ],
    "sourceUrl": "https://medium.com/@urbn_hq/why-real-estate-needs-an-identity-layer-85db804bae1d",
    "imageFit": "contain"
  },
  {
    "slug": "why-property-records-are-still-fragmented-in-nigeria",
    "title": "Why Property Records Are Still Fragmented in Nigeria",
    "excerpt": "Let’s consider Tunde. He found a land in 2019. A half-plot in a developing part of Ibadan, sold to him by a man who had inherited it from his father. The…",
    "image": "/images/blog/why-property-records-are-still-fragmented-in-nigeria/0.webp",
    "imageAlt": "A modern house surrounded by separate property documents, under the headline 'Why Property Records Are Still Fragmented in Nigeria'",
    "category": "Property",
    "date": "2026-09-29",
    "readMins": 5,
    "body": [
      {
        "type": "p",
        "html": "Let’s consider Tunde.<br>He found a land in 2019. A half-plot in a developing part of Ibadan, sold to him by a man who had inherited it from his father. The seller had a survey plan. He had an old receipt from the original purchase, decades earlier. He had a signed agreement."
      },
      {
        "type": "p",
        "html": "Three years later, Tunde wanted to build. His lawyer ran a proper search before the paperwork went to the bank for financing.<br>The survey plan checked out. But the registry had no record connecting that survey to the name on Tunde’s agreement — because the land had changed hands once before the seller’s father ever bought it, and that transaction had never been formally logged anywhere Tunde’s lawyer could find."
      },
      {
        "type": "p",
        "html": "The receipt existed. The survey existed. The agreement existed.<br>What didn’t exist was a clear chain connecting them into one complete history.<br>Nothing about Tunde’s documents was necessarily fake. They simply didn’t add up to a complete picture."
      },
      {
        "type": "p",
        "html": "This is the quieter problem behind Nigeria’s property records. It isn’t always that documents are missing. It is that having documents and having a connected history of a property are two different things — and Nigeria’s system has spent decades producing the first without reliably producing the second."
      },
      {
        "type": "h",
        "text": "A property has more than one record"
      },
      {
        "type": "p",
        "html": "A property generates information at different points in its life.<br>A survey describes its boundaries and location. A title record establishes a legal interest. A transaction creates a document of its own. A mortgage, a transfer, a subdivision, a planning approval — each adds another layer, often filed somewhere different from the one before it.<br>Each record answers a narrow question."
      },
      {
        "type": "p",
        "html": "None of them, alone, answers the one a buyer, a lender, or a legal professional ultimately needs to establish: what is the full story of this property, and do the records in front of me actually belong to the same property?"
      },
      {
        "type": "p",
        "html": "That&#39;s where Tunde&#39;s transaction ran into trouble. Every individual document could have a legitimate purpose. The connective tissue between them wasn&#39;t there."
      },
      {
        "type": "img",
        "src": "/images/blog/why-property-records-are-still-fragmented-in-nigeria/1.webp",
        "alt": "Paper files piled on a desk next to a laptop, lit by a desk lamp"
      },
      {
        "type": "h",
        "text": "Why records become fragmented"
      },
      {
        "type": "p",
        "html": "Nigeria does not run one uniform property-record system.<br>Land administration is handled largely at the state level, with different processes, registries and degrees of digitisation from one state to the next. A single property can also pass through several institutions and professional actors over its lifetime — registries, survey offices, planning authorities, lawyers, banks, developers and successive owners."
      },
      {
        "type": "p",
        "html": "The result is fragmentation even when each institution is maintaining the records within its own remit.<br>And property is never static. Ownership changes. Land gets subdivided, financed, developed, inherited and resold. The record has to keep pace with those changes."
      },
      {
        "type": "p",
        "html": "When it doesn’t, every new transaction becomes an exercise in reconstruction."
      },
      {
        "type": "p",
        "html": "The Federal Ministry of Housing and Urban Development has identified fragmented land records and limited access to land information among the challenges facing land administration in Nigeria. Its Land4Growth programme is also focused on modernising land administration and improving access to land information."
      },
      {
        "type": "p",
        "html": "Digital records help but they don’t automatically connect to anything.<br>Digitisation matters. Searching a digital record beats searching a filing cabinet.<br>But scanning a document doesn’t tell a system what that document belongs to."
      },
      {
        "type": "p",
        "html": "If a survey lives in one digital system, a title in another, and a transaction history in a third — with no consistent way to confirm that all three describe the same parcel of land — the fragmentation hasn’t disappeared. It’s just moved from cabinets to screens."
      },
      {
        "type": "p",
        "html": "Tunde’s lawyer could search a registry in seconds. The search still couldn’t tell him everything he needed to know about the property’s history."
      },
      {
        "type": "p",
        "html": "Oyo State already runs digital services along these lines. Its property search tool is designed to surface information including ownership history, legal status and encumbrances. Its Digital Land Survey Plan Registry allows users to check whether a survey plan has been captured in the official system.<br>The state is also explicit that a successful survey search, on its own, does not prove current ownership or replace a full legal and physical review.<br>These are real, useful pieces of infrastructure.<br>What’s still missing is something that holds the pieces together."
      },
      {
        "type": "h",
        "text": "Why this matters beyond buying land"
      },
      {
        "type": "p",
        "html": "For an owner, a disconnected record can make it harder to establish what they have when they eventually need to sell, transfer or borrow against it."
      },
      {
        "type": "p",
        "html": "For a lawyer or surveyor, it can mean reconstructing a property’s history almost from scratch on every transaction instead of building on information that is already connected."
      },
      {
        "type": "p",
        "html": "For government, fragmented information can make planning, infrastructure decisions and land administration more difficult."
      },
      {
        "type": "p",
        "html": "And for a buyer like Tunde, the risk isn’t necessarily fraud. It can simply be a legitimate property whose story cannot be verified end to end — which, at the point of financing or resale, can become a problem either way."
      },
      {
        "type": "p",
        "html": "This is why property information is becoming an infrastructure question, not just a paperwork question."
      },
      {
        "type": "h",
        "text": "The missing piece is connection"
      },
      {
        "type": "p",
        "html": "Nigeria isn’t starting from zero.<br>There are registries, surveys, title records, digital land services, property databases and geographic information systems already in place, with more being built."
      },
      {
        "type": "p",
        "html": "The harder question is how documents that already exist can be made to consistently point back to the same property, so its history can be read as one story instead of reassembled, case by case, from fragments."
      },
      {
        "type": "p",
        "html": "That’s exactly what Urbn is doing — giving every property a persistent identity of its own — a reference its records can reliably point to, no matter how many hands the property passes through."
      },
      {
        "type": "p",
        "html": "Tunde’s land was real. His documents were real.<br>What his transaction was missing wasn’t paperwork but rather a connection between all of the paperwork."
      }
    ],
    "sourceUrl": "https://medium.com/@urbn_hq/why-property-records-are-still-fragmented-in-nigeria-ea776d3af439",
    "imageFit": "contain"
  },
  {
    "slug": "why-co-living-is-reshaping-nigerias-urban-housing-market",
    "title": "Why Co-living Is Reshaping Nigeria’s Urban Housing Market",
    "excerpt": "As rents keep increasing across Nigerian cities, many young adults are finding it hard to afford traditional apartments. Co-living, a modern model of shared…",
    "image": "/images/blog/why-co-living-is-reshaping-nigerias-urban-housing-market/0.webp",
    "imageAlt": "Aerial view of a Nigerian city neighbourhood with houses, trees and high-rise buildings",
    "category": "Coliving",
    "date": "2025-09-10",
    "readMins": 3,
    "body": [
      {
        "type": "p",
        "html": "As rents keep increasing across Nigerian cities, many young adults are finding it hard to afford traditional apartments. Co-living, a modern model of shared living spaces, is rapidly gaining ground nationwide. In these arrangements, residents each have private bedrooms but share common areas like kitchens and lounges. This setup appeals to urban dwellers looking for lower-cost, flexible, community-oriented housing. Instead of living alone, residents split rent and utilities while enjoying furnished homes."
      },
      {
        "type": "h",
        "text": "Nigeria’s Housing Crunch"
      },
      {
        "type": "p",
        "html": "Nigeria faces a massive housing challenge, an estimated 28 million-unit deficit as of 2023. In many urban areas, the demand far outweighs the supply, and rents are rising rapidly. Over 60% of Nigerians live in rental homes, often cramped and overcrowded. With limited affordable housing, many people are turning to co-living as a practical solution. It is emerging as one of the most visible real estate trends in Nigeria, helping to bridge the gap between limited incomes and rising rents."
      },
      {
        "type": "h",
        "text": "Why Co-living Is Gaining Traction"
      },
      {
        "type": "p",
        "html": "Co-living’s growth is driven mostly by economic and lifestyle shifts. Affordability is the major factor: by sharing a household, residents cut costs. A report by NM Partners shows that a co-living room in Lagos can rent for about 20–35% less than a similar private studio or one-bedroom apartment."
      },
      {
        "type": "p",
        "html": "Other key drivers include:"
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          "Community &amp; Convenience: Co-living communities foster social support, shared lounges, kitchens and even co-working areas help residents network and avoid isolation. By design, co-living attracts people who want to live with like-minded individuals, collaborate and share experiences.",
          "Flexibility: Co-living typically offers shorter stays and monthly payments, appealing to students, early-career professionals and remote workers. In short, Nigeria’s young, tech-savvy population appreciates the ease of booking through mobile apps that match roommates and handle reservations, and the option to switch locations without heavy penalties."
        ]
      },
      {
        "type": "h",
        "text": "Benefits Of Co-living In Nigeria"
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          "Cost Savings: Co-living spaces are significantly cheaper than independent rentals. Residents split rents and utilities, making core urban neighborhoods in Nigeria accessible.",
          "Built-in Community: Co-living fosters friendships and professional connections. Shared meals, co-working spaces, and group activities help tenants feel at home and safe. For individuals relocating, this community support can be invaluable.",
          "Flexibility: Co-living arrangements typically offer shorter stays and more flexible terms than traditional leases. Month-to-month or quarterly options suit people whose plans aren’t fixed."
        ]
      },
      {
        "type": "h",
        "text": "Challenges Of Co-living In Nigeria"
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          "Privacy and Trust: Sharing means less privacy which may not suit everyone. Not all renters are comfortable with roommates or sharing bathrooms. Co-living operators need robust vetting, background checks, personality matching, etc., to ensure residents are safe. Additionally, disagreements over cleanliness, noise or bill-splitting can arise among strangers. Operators must manage these social dynamics carefully.",
          "Regulatory &amp; Legal Issues: No clear framework for co-living contracts yet, due to the fact that Nigeria’s housing and tenancy laws do not explicitly address co-living. Complexities in lease agreements or property rights can cause confusion.",
          "Social/Cultural Fit: Some Nigerians still prefer owning or renting a whole house even though the country’s inflation prevents this. Convincing them of shared living can be a mindset shift."
        ]
      },
      {
        "type": "p",
        "html": "Co-living is an adaptive response to a critical problem: the housing crisis in Nigeria. By combining affordability, convenience, and community, co-living is reshaping Nigeria’s real estate sector. For investors, entrepreneurs, and real estate experts, this represents an untapped opportunity. The demand for affordable housing in Nigeria is undeniable, and co-living is one of the most promising solutions. In the coming years, we can expect more developers to enter this space, more standardized co-living regulations, and possibly new financing models."
      }
    ],
    "sourceUrl": "https://medium.com/@urbn_hq/why-co-living-is-reshaping-nigerias-urban-housing-market-1ab859be7cd1"
  },
  {
    "slug": "a-landlords-guide-to-property-documentation-and-lease-agreements-in-nigeria",
    "title": "A Landlord’s Guide to Property Documentation and Lease Agreements in Nigeria",
    "excerpt": "A practical guide for Nigerian landlords on property documentation and lease agreements. Learn tenancy laws, tenant rights, key documents, and legal tips to…",
    "image": "/images/blog/a-landlords-guide-to-property-documentation-and-lease-agreements-in-nigeria/0.webp",
    "imageAlt": "A landlord signing a lease agreement at a desk, with the article title overlaid",
    "category": "Business",
    "date": "2025-09-08",
    "readMins": 7,
    "body": [
      {
        "type": "p",
        "html": "<em>A practical guide for Nigerian landlords on property documentation and lease agreements. Learn tenancy laws, tenant rights, key documents, and legal tips to protect your investment.</em>"
      },
      {
        "type": "p",
        "html": "In Nigeria’s complex property market, tenancy laws in Nigeria require landlords to complete paperwork and clear rental contracts. Under federal laws like the Land Use Act (1978) and state tenancy laws (e.g. Lagos Tenancy Law 2011), a lease agreement in Nigeria must spell out rent, duration, notice periods and each party’s duties. Whether you are a new or experienced landlord, understanding these laws and preparing the right property documents will help safeguard your investment and prevent costly disputes."
      },
      {
        "type": "h",
        "text": "Understanding Nigeria’s Legal Framework"
      },
      {
        "type": "p",
        "html": "Nigeria’s land laws are governed by a mix of federal and state rules. The LAnd Use Act 1978 vests all land in each state’s governor (held in trust for the people) and provides the basis for titles like Certificates of Occupancy (C of O). On top of this, each state has its own tenancy or rent control law. For example, Lagos State uses the Tenancy Law of 2011 (Law №14) to regulate leases, while the FCT (Abuja) falls under the recovery of Premises Act. Other states rely on older Rent Control and Recovery of Premises Laws. These laws collectively govern landlord and tenant rights; they set limits on advance rent, outline eviction procedures, and require written agreements and receipts for rent. Before drafting any lease agreement in Nigeria, confirm the specific tenancy law for your state, as requirements (like notice periods) can differ slightly."
      },
      {
        "type": "h",
        "text": "Essential Property Documents"
      },
      {
        "type": "p",
        "html": "Before renting out a property, ensure you have complete title and approval documents. Key items include:"
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          "<strong>Title Documents: </strong>The Certificate of Occupancy (C of O) or Deed of Assignment is proof you own the land. The CofO is issued by the state governor and evidences your right to lease the land. If you bought the property, a registered Deed of Assignment should be on file, showing the seller transferred ownership to you. Make sure all titles are registered and properly stamped.",
          "<strong>Survey Plan: </strong>A registered survey plan shows the exact boundaries and dimensions of the property. It must be prepared by a licensed surveyor and approved by the State Surveyor-General. A current survey plan prevents boundary disputes by confirming the land you’re leasing is correctly described.",
          "<strong>Approved Building Plans and Permits: </strong>Approved building plans (from the local planning authority) and a completion certificate demonstrate that the structure is legally built. Always verify that the existing building has official approval; leasing out a home without proper permits can lead to fines or demolition orders.",
          "<strong>Tax and Fee Receipts:</strong> Keep receipts or certificates for any property levies (ground rent, land use charge, tenement rates) and tax clearances. For example, when transferring a title, Nigerian law requires three years of tax clearance of both assignor and assignee. Even if you’re only leasing, maintain proof of paid government dues (e.g. development levy receipts, land use charge) to show the property is in good standing.",
          "<strong>Power of Attorney (if applicable):</strong> If you use an agent or a representative (for example, if you live abroad), a notarized power of attorney is needed to authorize that person to sign the lease and handle payments on your behalf. This ensures any agent’s actions are legally binding for you."
        ]
      },
      {
        "type": "p",
        "html": "By having all property documents in Nigeria — title, survey, approvals, tax proofs, etc. — organized and ready, you’ll avoid headaches (and possible legal penalties) down the road."
      },
      {
        "type": "h",
        "text": "Key Components of a Lease Agreement"
      },
      {
        "type": "p",
        "html": "A well-drafted lease agreement in Nigeria should clearly spell out all essential terms. Include the following clauses:"
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          "<strong>Parties &amp; Properties:</strong> Identify the landlord and tenant by full name and address. Describe the property in detail (address, flat or house number, and any included facilities)",
          "<strong>Lease Duration:</strong> State the start and end dates of the lease (fixed-term) or note if it rolls over monthly/quarterly. A fixed-term (e.g. 1 year) should have clear renewal terms.",
          "<strong>Rent &amp; Payment Terms:</strong> Specify the rent amount, due dates, payment method (bank transfer, cheque, etc.), and grace period for late payment. For example: <em>“Rent is 1,200,000 NGN per year, payable in two installments on Jan 1 and July 1”.</em>",
          "<strong>Security Deposit: </strong>State the deposit amount (often 1–2 months’ rent) and conditions for refund. Under Nigerian practice, landlords must return the deposit (minus agreed deductions for damages or unpaid rent) at lease end.",
          "<strong>Repairs &amp; Maintenance: </strong>Clarify who repairs. Typically, tenants handle minor upkeep (lightbulbs, loose handles), while landlords are responsible for major structural repairs (wall, roofing, plumbing). E.g. <em>“Tenants shall fix damages they cause; Landlords will repair major plumbing/electrical faults.”.</em>",
          "<strong>Use &amp; Restrictions: </strong>Specify how the property may be used (residential only, or commercial). Address issues like subletting: many landlords prohibit subletting without written consent.",
          "<strong>Termination &amp; Notice: </strong>Set out how either party can end the lease early and the notice required. Under the Lagos State tenancy law, if the agreement itself is silent, notice is one month for monthly rentals, three months for quarterly rentals or half-yearly, and six months for yearly rentals.",
          "<strong>Default &amp; Breach: </strong>Include remedies if rent isn’t paid or other terms are violated (e.g. late fees, forfeiture of deposit, or eviction). Make c;ear that any eviction or termination must follow the law.",
          "<strong>Dispute Resolution: </strong>It is wise to add a clause about handling disputes. This can save time and money if conflicts arise."
        ]
      },
      {
        "type": "p",
        "html": "Ensure your lease complies with Nigerian Law. For instance, any lease over three years must generally be in writing, and the document must be stamped by the Nigerian IRS to be enforceable. By covering these components in your lease, you create a legally sound agreement that protects both parties."
      },
      {
        "type": "h",
        "text": "Issuing Receipts and Keeping Records"
      },
      {
        "type": "p",
        "html": "One of the most important but sometimes overlooked obligations is issuing rent receipts. Under Lagos State law, landlords must provide written receipts whenever rent is paid. These receipts should show the date, amount paid, and the property’s address. Failure to issue a receipt is a criminal offence in Lagos, punishable by a 100,000. The same rule applies to any other payment required by the lease, for example, if the lease demands a security deposit or service charge, the landlord must give a separate receipt for those payments and keep an account of how the funds are used (with an accounting to the tenant at least every 6 months)."
      },
      {
        "type": "p",
        "html": "<strong>Why this matters: </strong>Rent receipts are proof of payment. They protect you if a tenant later denies paying or claims overpayment. Keeping clear records (receipts, a rent roll, payment logs) also helps you track income and avoid disputes. As one legal guide warns, landlords who neglect receipts “make it harder to prove terms in court”."
      },
      {
        "type": "h",
        "text": "Tenant Right and Landlord Obligations"
      },
      {
        "type": "p",
        "html": "Understanding tenant rights is as important as knowing your own duties. Nigerian tenancy laws balance both sides."
      },
      {
        "type": "p",
        "html": "Tenants are entitled to quiet and exclusive enjoyment of the premises. This means landlords must not harass or unduly disturb them, entry should only be by appointment (and emergency cases excepted). Tenants also have the right to a formal tenancy agreement and to be given proper notice before eviction. For example, they cannot be locked out or evicted without a court order. Any self-help eviction (changing locks, cutting utilities, etc.) is illegal, and landlords who attempt it risk fines and imprisonment."
      },
      {
        "type": "p",
        "html": "Tenants cannot be forced to pay more than six months rent in advance if they are monthly tenants, or one year if they are yearly tenants. Landlords may only collect at most one year’s rent from new or existing tenants. Tenants have the right to a written receipt for every payment."
      },
      {
        "type": "p",
        "html": "Tenants have exclusive possession and may use common areas reasonably. They also have the right to compensation for any approved improvements they make when the lease ends."
      },
      {
        "type": "p",
        "html": "<strong>Landlord Obligations: </strong>By Law, landlords must maintain the property in good condition. Specifically, the landlord is required to keep the building insured and to “effect repairs and maintain the external and common parts of the premises”. In practice, this means taking care of major structural repairs, plumbing, and other essential services so the home remains habitable. Landlords must also pay property rates and ground rent charged by the government."
      },
      {
        "type": "p",
        "html": "A landlord cannot demand payments not agreed in the lease. Do not seize tenant property or interfere with their personal space. Any eviction or termination must follow the legal process. Both landlords and tenants benefit when obligations are met. Meeting your obligations builds trust and reduces conflict. It also protects your right as a landlord."
      },
      {
        "type": "p",
        "html": "For Nigerian landlords, clear documentation and compliance with tenancy laws are the best safeguards. Before signing any lease agreement, double check that your property documents are in order and that the lease covers rent, duration, notice, and responsibilities as required by law. Always issue receipts for payments and respect tenant rights to avoid disputes down the line."
      },
      {
        "type": "p",
        "html": "Protect your investment and legal rights by acting proactively. Consider consulting a property lawyer before finalizing any lease. Taking these steps now will help you avoid costly problems later, ensuring a smooth professional landlors-tenant relationship."
      }
    ],
    "sourceUrl": "https://medium.com/@urbn_hq/a-landlords-guide-to-property-documentation-and-lease-agreements-in-nigeria-c73ea917c8cb"
  }
];
