// Seed marketplace data in the exact shape the Urbn API returns. Used when
// URBN_API_URL is not configured (local dev, previews, pre-launch builds).
import { makeDpi } from "../dpi";
import type { ListingDetail } from "./types";

const IMG = {
  white: "/images/house-result.webp",
  identity: "/images/house-identity.webp",
  plaque: "/images/house-plaque.webp",
  modern: "/images/house-modern.webp",
  block: "/images/hero-billboard.webp",
  gate: "/images/plaque-scene.webp",
};

type Seed = Partial<ListingDetail> &
  Pick<ListingDetail, "id" | "listingType" | "price" | "rentPeriod" | "propertyTitle" | "propertyAddress" | "propertyBuildingType" | "latitude" | "longitude" | "lga" | "images"> & {
    beds: number;
    baths: number;
    seq: number;
  };

const agent = (id: string, displayName: string, agencyName: string | null, rating: number, reviewCount: number) => ({
  id,
  displayName,
  agencyName,
  profileImageUrl: null,
  rating,
  reviewCount,
});

const SEEDS: Seed[] = [
  {
    id: "lst-olatunde-house",
    seq: 41,
    lga: "Ibadan North",
    listingType: "Rent",
    price: 3_500_000,
    rentPeriod: "Yearly",
    propertyTitle: "Olatunde House",
    propertyAddress: "41A Adeyemo Street, Bodija",
    propertyBuildingType: "Duplex",
    structureType: "Detached Duplex",
    latitude: 7.4296,
    longitude: 3.9107,
    beds: 4,
    baths: 5,
    squareFootage: 220,
    images: [IMG.white, IMG.plaque, IMG.identity],
    isFeatured: true,
    views: 2140,
    likeCount: 214,
    saveCount: 96,
    commentCount: 12,
    furnishingStatus: "SemiFurnished",
    deposit: 350_000,
    serviceCharge: 250_000,
    legalFee: 175_000,
    isNegotiable: false,
    minLeaseTerm: 12,
    immediateAvailability: true,
    allowPets: true,
    inspectionType: "BOTH",
    inspectionFeeKobo: 0,
    keyFeatures: "Four en-suite bedrooms\nFitted kitchen with pantry\nOne-room BQ with separate entrance\nPrepaid meter and borehole\nParking for three cars",
    requirements: ["Valid means of ID", "Employment or business reference", "One year's rent upfront"],
    description:
      "A bright, detached four-bedroom duplex on a quiet, gated street minutes from Bodija Market and the University of Ibadan. Every bedroom is en-suite, the kitchen is fully fitted, and there's a one-room BQ with its own entrance.",
    securityFeatures: ["GatedEntry", "SecurityCameras"],
    outdoorFeatures: ["Patio"],
    waterSources: ["Borehole"],
    electricitySources: ["Prepaid meter", "Inverter"],
    agent: null,
    propertyVideoUrl: "video",
    createdAt: "2026-03-12T09:00:00Z",
  },
  {
    id: "lst-romi-tayo-house",
    seq: 12,
    lga: "Lagelu",
    listingType: "Rent",
    price: 1_800_000,
    rentPeriod: "Yearly",
    propertyTitle: "Romi Tayo House",
    propertyAddress: "Kolapo Ishola Estate, Akobo",
    propertyBuildingType: "BlockOfFlats",
    structureType: "3 Bedroom Flat",
    latitude: 7.4345,
    longitude: 3.9531,
    beds: 3,
    baths: 3,
    squareFootage: 135,
    unitCount: 6,
    isMainUnit: false,
    images: [IMG.block, IMG.identity, IMG.white],
    isFeatured: true,
    views: 1620,
    likeCount: 162,
    saveCount: 71,
    commentCount: 8,
    furnishingStatus: "Unfurnished",
    deposit: 180_000,
    serviceCharge: 300_000,
    legalFee: 90_000,
    isNegotiable: true,
    minLeaseTerm: 12,
    maxLeaseTerm: 24,
    immediateAvailability: false,
    availableFrom: "2026-11-01",
    allowPets: false,
    inspectionType: "BOTH",
    inspectionFeeKobo: 500_000,
    keyFeatures: "Second-floor flat in a serviced six-unit block\n24-hour estate security\nShared power backup\nWardrobes in every room",
    requirements: ["Valid means of ID", "Guarantor form"],
    description:
      "A spacious three-bedroom flat on the second floor of a serviced, six-unit block inside Kolapo Ishola Estate. The building is managed on-site, with shared power backup and 24-hour security at the estate gate. The DPI covers the whole building, and each flat is logged as a unit under it.",
    securityFeatures: ["GatedEntry", "GuardHouse"],
    outdoorFeatures: [],
    waterSources: ["Borehole"],
    electricitySources: ["Prepaid meter", "Generator"],
    agent: agent("ag-tayo", "Tayo Adebisi", "Tayo Homes Ltd", 4.8, 37),
    propertyVideoUrl: "video",
    createdAt: "2026-04-02T09:00:00Z",
  },
  {
    id: "lst-aso-rock-court",
    seq: 7,
    lga: "Ibadan North-West",
    listingType: "Rent",
    price: 1_200_000,
    rentPeriod: "Yearly",
    propertyTitle: "Aso Rock Court",
    propertyAddress: "7B Jericho GRA, Jericho",
    propertyBuildingType: "Apartment",
    structureType: "2 Bedroom Flat",
    latitude: 7.4032,
    longitude: 3.8696,
    beds: 2,
    baths: 2,
    squareFootage: 90,
    unitCount: 4,
    isMainUnit: false,
    images: [IMG.identity, IMG.block, IMG.white],
    views: 880,
    likeCount: 88,
    saveCount: 40,
    commentCount: 3,
    furnishingStatus: "Unfurnished",
    deposit: 120_000,
    serviceCharge: 150_000,
    legalFee: 60_000,
    isNegotiable: true,
    minLeaseTerm: 12,
    immediateAvailability: true,
    allowPets: false,
    inspectionType: "PHYSICAL",
    inspectionFeeKobo: 0,
    keyFeatures: "Both bedrooms en-suite\nGuest toilet\nBalcony overlooking the trees",
    requirements: ["Valid means of ID"],
    description:
      "A well-kept two-bedroom flat in a compact, gated block in Jericho GRA. The agent's authority to list this property is logged against its DPI, so you know who you're dealing with before you send a naira.",
    securityFeatures: ["GatedEntry"],
    outdoorFeatures: ["Porch"],
    waterSources: ["Borehole"],
    electricitySources: ["Prepaid meter"],
    agent: agent("ag-kunle", "Kunle Adebayo", null, 4.6, 19),
    createdAt: "2026-02-20T09:00:00Z",
  },
  {
    id: "lst-aerodrome-duplex",
    seq: 22,
    lga: "Akinyele",
    listingType: "Sale",
    price: 185_000_000,
    rentPeriod: null,
    propertyTitle: "Aerodrome Estate Duplex",
    propertyAddress: "22 Aerodrome Estate, Samonda",
    propertyBuildingType: "Duplex",
    structureType: "Detached Duplex",
    latitude: 7.4402,
    longitude: 3.8997,
    beds: 4,
    baths: 5,
    squareFootage: 140,
    images: [IMG.plaque, IMG.white, IMG.modern],
    isFeatured: true,
    views: 3010,
    likeCount: 301,
    saveCount: 154,
    commentCount: 22,
    furnishingStatus: "Unfurnished",
    legalFee: 9_250_000,
    isNegotiable: true,
    immediateAvailability: true,
    inspectionType: "BOTH",
    inspectionFeeKobo: 0,
    keyFeatures: "Certificate of Occupancy\nSolar power backup\nLandscaped garden\nOne-room BQ",
    requirements: ["Proof of funds before second inspection"],
    description:
      "A modern four-bedroom detached duplex with a Certificate of Occupancy, solar power backup and a landscaped garden. The property's ownership history starts with its DPI, so every future sale or tenancy is logged on the same record.",
    securityFeatures: ["GatedEntry", "MotionLights"],
    outdoorFeatures: ["Patio", "Gazebo"],
    waterSources: ["Borehole"],
    electricitySources: ["Solar", "Prepaid meter"],
    agent: null,
    propertyVideoUrl: "video",
    createdAt: "2026-01-28T09:00:00Z",
  },
  {
    id: "lst-oluyole-mini-flat",
    seq: 3,
    lga: "Ibadan South-West",
    listingType: "Rent",
    price: 650_000,
    rentPeriod: "Yearly",
    propertyTitle: "Oluyole Mini Flat",
    propertyAddress: "3 Oluyole Estate Extension, Oluyole",
    propertyBuildingType: "MiniFlat",
    structureType: "Mini Flat",
    latitude: 7.3637,
    longitude: 3.8622,
    beds: 1,
    baths: 1,
    squareFootage: 45,
    isMainUnit: false,
    unitCount: 8,
    images: [IMG.gate, IMG.identity, IMG.block],
    views: 470,
    likeCount: 47,
    saveCount: 22,
    commentCount: 1,
    furnishingStatus: "Unfurnished",
    deposit: 65_000,
    legalFee: 32_500,
    minLeaseTerm: 12,
    immediateAvailability: true,
    inspectionType: "PHYSICAL",
    inspectionFeeKobo: 0,
    keyFeatures: "Own kitchen and bathroom\nQuiet, fenced compound",
    requirements: ["Valid means of ID"],
    description: "A neat one-bedroom mini flat with its own kitchen and bathroom in a quiet, fenced compound. Good value for a first home.",
    securityFeatures: [],
    outdoorFeatures: [],
    waterSources: ["Well"],
    electricitySources: ["Prepaid meter"],
    agent: null,
    createdAt: "2026-05-09T09:00:00Z",
  },
  {
    id: "lst-samonda-studio",
    seq: 18,
    lga: "Akinyele",
    listingType: "Rent",
    price: 380_000,
    rentPeriod: "Yearly",
    propertyTitle: "Samonda Studio",
    propertyAddress: "18 Samonda, near UI second gate",
    propertyBuildingType: "Apartment",
    structureType: "Self Contain",
    latitude: 7.4443,
    longitude: 3.8962,
    beds: 1,
    baths: 1,
    squareFootage: 28,
    isMainUnit: false,
    unitCount: 10,
    images: [IMG.identity, IMG.gate, IMG.white],
    views: 1290,
    likeCount: 129,
    saveCount: 88,
    commentCount: 9,
    furnishingStatus: "SemiFurnished",
    deposit: 38_000,
    minLeaseTerm: 12,
    immediateAvailability: true,
    inspectionType: "BOTH",
    inspectionFeeKobo: 200_000,
    keyFeatures: "Kitchenette\nEn-suite bathroom\nWalking distance to UI",
    requirements: ["Valid means of ID", "Student ID or employment letter"],
    description: "A self-contained studio with a kitchenette and en-suite bathroom, a few minutes' walk from the University of Ibadan's second gate.",
    securityFeatures: ["GuardHouse"],
    outdoorFeatures: [],
    waterSources: ["Borehole"],
    electricitySources: ["Prepaid meter"],
    agent: agent("ag-femi", "Femi Ogunleye", null, 4.4, 11),
    propertyVideoUrl: "video",
    createdAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "lst-ring-road-terrace",
    seq: 22,
    lga: "Ibadan South-West",
    listingType: "Lease",
    price: 2_400_000,
    rentPeriod: "Yearly",
    propertyTitle: "Ring Road Terrace",
    propertyAddress: "5 Crest Close, Ring Road",
    propertyBuildingType: "Terrace",
    structureType: "3 Bedroom Terrace",
    latitude: 7.3728,
    longitude: 3.8824,
    beds: 3,
    baths: 4,
    squareFootage: 160,
    isMainUnit: false,
    unitCount: 8,
    images: [IMG.modern, IMG.plaque, IMG.identity],
    views: 960,
    likeCount: 96,
    saveCount: 39,
    commentCount: 4,
    furnishingStatus: "Unfurnished",
    deposit: 240_000,
    serviceCharge: 360_000,
    legalFee: 120_000,
    minLeaseTerm: 24,
    maxLeaseTerm: 60,
    immediateAvailability: true,
    inspectionType: "BOTH",
    inspectionFeeKobo: 0,
    keyFeatures: "Gated estate of eight homes\nFitted kitchen\nTwo parking spaces",
    requirements: ["Valid means of ID", "Company letter for corporate leases"],
    description: "A three-bedroom terrace in a gated estate of eight homes off Ring Road, available on a two-to-five-year lease.",
    securityFeatures: ["GatedEntry", "SecurityCameras"],
    outdoorFeatures: ["Porch"],
    waterSources: ["Borehole"],
    electricitySources: ["Prepaid meter", "Generator"],
    agent: agent("ag-crest", "Bola Ajayi", "Crest Estates", 4.9, 52),
    propertyVideoUrl: "video",
    createdAt: "2026-03-30T09:00:00Z",
  },
  {
    id: "lst-bodija-shortlet",
    seq: 58,
    lga: "Ibadan North",
    listingType: "ShortTermRental",
    price: 55_000,
    rentPeriod: "Daily",
    propertyTitle: "Bodija Shortlet Suites",
    propertyAddress: "9 New Bodija Estate, Bodija",
    propertyBuildingType: "Apartment",
    structureType: "2 Bedroom Apartment",
    latitude: 7.4362,
    longitude: 3.9156,
    beds: 2,
    baths: 2,
    squareFootage: 85,
    isMainUnit: false,
    unitCount: 4,
    images: [IMG.block, IMG.white, IMG.modern],
    isFeatured: true,
    views: 1880,
    likeCount: 188,
    saveCount: 120,
    commentCount: 15,
    furnishingStatus: "Furnished",
    inventoryCount: 46,
    deposit: 50_000,
    immediateAvailability: true,
    allowPets: false,
    inspectionType: "VIRTUAL",
    inspectionFeeKobo: 0,
    keyFeatures: "24/7 power\nFast Wi-Fi\nAir conditioning in every room\nWeekly housekeeping",
    requirements: ["Valid means of ID at check-in"],
    description: "A fully serviced two-bedroom shortlet with round-the-clock power, fast Wi-Fi and weekly housekeeping. Ideal for business trips and family visits.",
    securityFeatures: ["GatedEntry", "SecurityCameras", "GuardHouse"],
    outdoorFeatures: [],
    waterSources: ["Borehole"],
    electricitySources: ["Generator", "Inverter"],
    agent: agent("ag-stay", "Ada Okafor", "Stay Ibadan", 4.9, 88),
    propertyVideoUrl: "video",
    createdAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "lst-akobo-bungalow",
    seq: 27,
    lga: "Egbeda",
    listingType: "Sale",
    price: 68_000_000,
    rentPeriod: null,
    propertyTitle: "Akobo Garden Bungalow",
    propertyAddress: "27 Odejayi Road, Akobo",
    propertyBuildingType: "Bungalow",
    structureType: "3 Bedroom Bungalow",
    latitude: 7.4271,
    longitude: 3.9622,
    beds: 3,
    baths: 3,
    squareFootage: 120,
    images: [IMG.gate, IMG.modern, IMG.white],
    views: 640,
    likeCount: 64,
    saveCount: 31,
    commentCount: 2,
    furnishingStatus: "Unfurnished",
    legalFee: 3_400_000,
    isNegotiable: true,
    immediateAvailability: true,
    inspectionType: "PHYSICAL",
    inspectionFeeKobo: 0,
    keyFeatures: "Registered survey and deed of assignment\nLarge, fenced plot with room to extend\nBorehole",
    requirements: ["Proof of funds before second inspection"],
    description: "A solid three-bedroom bungalow on a large, fenced plot with room to extend.",
    securityFeatures: ["GatedEntry"],
    outdoorFeatures: ["Shed"],
    waterSources: ["Borehole"],
    electricitySources: ["Prepaid meter"],
    agent: agent("ag-grace", "Grace Olawale", null, 4.7, 23),
    createdAt: "2026-04-18T09:00:00Z",
  },
];

export const SEED_LISTINGS: ListingDetail[] = SEEDS.map(({ beds, baths, seq, ...s }) => ({
  status: "ACTIVE",
  isFeatured: false,
  views: 0,
  likeCount: 0,
  saveCount: 0,
  commentCount: 0,
  isAcceptingInspections: true,
  expiresAt: null,
  unitId: `${s.id}-unit`,
  propertyId: `${s.id}-prop`,
  isMainUnit: true,
  squareFootage: null,
  propertyCity: "Ibadan",
  propertyState: "Oyo",
  thumbnailUrl: s.images[0],
  agent: null,
  propertyVideoUrl: null,
  propertyVideoPosterUrl: null,
  listingVideoUrl: null,
  listingVideoPosterUrl: null,
  structureType: null,
  roomCount: beds + baths,
  unitCount: null,
  description: null,
  publishedAt: s.createdAt ?? null,
  isVerified: true,
  rooms: null,
  securityFeatures: [],
  outdoorFeatures: [],
  waterSources: [],
  electricitySources: [],
  createdAt: "2026-01-01T09:00:00Z",
  ...s,
  roomSummary: [
    { roomType: "Bedroom", count: beds },
    { roomType: "Bathroom", count: baths },
  ],
  dpi: makeDpi(s.lga!, seq),
  // Sample reels (public/videos/reels), made from the listing's own photos.
  ...(s.propertyVideoUrl
    ? { propertyVideoUrl: `/videos/reels/${s.id}.mp4`, propertyVideoPosterUrl: `/videos/reels/${s.id}.jpg` }
    : {}),
}));
