import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("dpi", "routes/dpi.tsx"),
  route("verify", "routes/verify.tsx"),
  route("verify/:code/:unit?", "routes/verify-result.tsx"),
  route("p/dpi/:code/:unit?", "routes/verify-result.tsx", { id: "plaque-landing" }),
  // Universal link the app shares and the plaque QR opens (apple-app-site-association / assetlinks.json).
  route("property/dpi/:code/:unit?", "routes/verify-result.tsx", { id: "dpi-link" }),
  route("listing/:id", "routes/listing-link.ts"),
  route("features", "routes/features.tsx"),
  route("listings", "routes/listings.tsx"),
  route("listings/in/:place", "routes/listings-place.tsx"),
  route("listings/:id/:slug?", "routes/listing.tsx"),
  route("reels", "routes/reels.tsx"),
  route("reels/:id/:slug?", "routes/reels.tsx", { id: "reel" }),
  route("nearby", "routes/nearby.tsx"),
  route("nearby/in/:area/:category?", "routes/nearby-hub.tsx"),
  route("nearby/activity/:id/:slug?", "routes/nearby-activity.tsx"),
  route("about", "routes/about.tsx"),
  route("faq", "routes/faq.tsx"),
  route("blog", "routes/blog.tsx"),
  route("blog/:slug", "routes/blog-post.tsx"),
  route("for-renters", "routes/audience.tsx", { id: "for-renters" }),
  route("for-owners", "routes/audience.tsx", { id: "for-owners" }),
  route("for-agents", "routes/audience.tsx", { id: "for-agents" }),
  route("download", "routes/download.tsx"),
  route("contact", "routes/contact.tsx"),
  route("careers", "routes/careers.tsx"),
  route("terms", "routes/legal.tsx", { id: "terms" }),
  route("privacy", "routes/legal.tsx", { id: "privacy" }),

  // resource routes
  route("api/listings", "routes/api.listings.ts"),
  route("api/listings/ai-search", "routes/api.ai-search.ts"),
  route("api/dpi/:code/:unit?", "routes/api.dpi.ts"),
  route("api/reels", "routes/api.reels.ts"),
  route("api/reels/:id/comments", "routes/api.reel-comments.ts"),
  route("api/nearby", "routes/api.nearby.ts"),
  route("api/nearby/:id", "routes/api.nearby-place.ts"),
  route("api/waitlist", "routes/api.waitlist.ts"),
  route("api/ubeep/*", "routes/api.ubeep.ts"),
  route("sitemap.xml", "routes/sitemap.xml.ts"),
  route("robots.txt", "routes/robots.txt.ts"),

  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
